# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Rented', 'Rented'), ('Returned', 'Returned')], max_length=50)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Customer')),
            ],
        ),
    ]
