# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20170212_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRentProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'Active rent',
            },
            bases=('management.rent',),
        ),
        migrations.AddField(
            model_name='car',
            name='cost',
            field=models.TextField(blank=True, default='100$', null=True),
        ),
    ]
