# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20170212_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='auto_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='management.Car'),
        ),
    ]
