# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20170214_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cost',
            field=models.CharField(blank=True, default='100$', max_length=50, null=True),
        ),
    ]
